openapi: 3.0.1
info:
  title: zabbix_rest_api_open_api_3
  description: My cool app
  version: 1.0.0
servers:
  - url: /api/v1
tags:
  - name: Zabbix
    description: Zabbix API
  - name: Specification
    description: The swagger API specification
paths:
  /zabbix/login:
    post:
      tags:
        - Zabbix
      requestBody:
        description: login body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
      responses:
        200:
          description: Return user info
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Login200'
        4XX:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        5XX:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /zabbix/logout:
    get:
      tags:
        - Zabbix
      responses:
        200:
          description: Boolean
          content: {}

  /zabbix/hosts:
    get:
      tags:
        - Zabbix
      responses:
        200:
          description: Returns array of hosts
          content: {}

  /zabbix/maps:
    post:
      tags:
        - Zabbix
      description: Create trigger maps for array of hostid
      requestBody:
        description: array of hostid
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateMaps'
        required: true
      responses:
        200:
          description: Returns array of objects with sysmapids array property
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateMaps200'
        4XX:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        5XX:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification
          content: {}

components:
  schemas:
    Login:
      type: object
      properties:
        url:
          type: string
          example: '127.0.0.1'
        username:
          type: string
          example: 'Admin'
        password:
          type: string
          example: 'zabbix'
          
    Login200:
      type: object
      properties:
        userid:
          type: integer
          example: 1
        alias:
          type: string
          example: 'Admin'
        name:
          type: string
          example: 'Zabbix'
        surname:
          type: string
          example: 'Administrator'
        url:
          type: string
          example: ''
        autologin:
          type: string
          example: '1'
        autologout:
          type: string
          example: '0'
        lang:
          type: string
          example: 'en_GB'
        refresh:
          type: string
          example: '30s'
        type:
          type: string
          example: '3'
        theme:
          type: string
          example: 'default'
        attempt_failed:
          type: string
          example: '0'
        attempt_ip:
          type: string
          example: '172.20.240.0'
        attempt_clock:
          type: string
          example: "1603294197"
        rows_per_page:
          type: string
          example: '50'
        sessionid:
          type: string
          example: "db4b5ac343ce638055e694f946d48307"
        debug_mode:
          type: integer
          example: 0
        userip:
          type: string
          example: '172.20.240.0'
        gui_access:
          type: integer
          example: 0

    CreateMaps:
      type: object
      title: hostids array
      description: hostids array
      properties:
        hostids:
          items:
            type: integer
            enum:
              - 10084
    
    CreateMaps200:
      type: array
      title: array of objects with sysmapids array property
      description: array of objects with sysmapids array property
      items:
        type: object
        properties:
          sysmapids:
            type: array
            items:
              type: integer
              enum:
                - 42

    Error:
      type: array
      title: array of error objects
      description: array of error objects
      items:
        type: object
        properties:
          error:
            type: object
            additionalProperties: true
