openapi: 3.0.1
info:
  title: zabbix_rest_api_open_api_3
  description: My cool app
  version: 1.0.0
servers:
  - url: /api/v1
tags:
  - name: Specification
    description: The swagger API specification
paths:
  /zabbix/login:
    post:
      tags:
        - Zabbix
      requestBody:
        description: login body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginReq'
      responses:
        200:
          description: Return the API specification
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginRes'

  /zabbix/logout:
    get:
      tags:
        - Zabbix
      responses:
        200:
          description: Return the API specification
          content: {}
  /zabbix/hosts:
    get:
      tags:
        - Zabbix
      responses:
        200:
          description: Return the API specification
          content: {}
  /zabbix/map:
    post:
      tags:
        - Zabbix
      description: Create a new example
      requestBody:
        description: an example
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExampleMap'
        required: true
      responses:
        201:
          description: Return the example with the specified id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Example'
        4XX:
          description: Example not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        5XX:
          description: Example not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /zabbix/triggers:
    post:
      tags:
        - Zabbix
      description: Create a new example
      requestBody:
        description: an example
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExampleTriggers'
        required: true
      responses:
        201:
          description: Return the example with the specified id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Example'
        4XX:
          description: Example not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        5XX:
          description: Example not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /zabbix/prepare_images:
    get:
      tags:
        - Zabbix
      responses:
        200:
          description: Return the API specification
          content: {}
  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification
          content: {}
components:
  schemas:
    LoginReq:
      type: object
      properties:
        url:
          type: string
          example: '127.0.0.1'
        username:
          type: string
          example: 'Admin'
        password:
          type: string
          example: 'zabbix'
    LoginRes:
      type: object
      properties:
        userid:
          type: integer
          example: 1
        alias:
          type: string
          example: 'Admin'
        name:
          type: string
          example: 'Zabbix'
        surname:
          type: string
          example: 'Administrator'
        url:
          type: string
          example: ''
        autologin:
          type: string
          example: '1'
        autologout:
          type: string
          example: '0'
        lang:
          type: string
          example: 'en_GB'
        refresh:
          type: string
          example: '30s'
        type:
          type: string
          example: '3'
        theme:
          type: string
          example: 'default'
        attempt_failed:
          type: string
          example: '0'
        attempt_ip:
          type: string
          example: '172.20.240.0'
        attempt_clock:
          type: string
          example: "1603294197"
        rows_per_page:
          type: string
          example: '50'
        sessionid:
          type: string
          example: "db4b5ac343ce638055e694f946d48307"
        debug_mode:
          type: integer
          example: 0
        userip:
          type: string
          example: '172.20.240.0'
        gui_access:
          type: integer
          example: 0
    Example:
      type: object
      properties:
        id:
          type: integer
          example: 3
        name:
          type: string
          example: example 3
    Error:
      type: object
      additionalProperties: true

    ExampleBody:
      title: example
      required:
        - name
      type: object
      properties:
        name:
          type: string
          example: no_stress

    ExampleMap:
      type: object
      title: ''
      description: ' Entity'
      properties:
        name:
          type: string
          example: TEST5 Trigger map
        width:
          type: integer
          example: 600
        height:
          type: integer
          example: 600
        selements:
          type: array
          items:
            $ref: '#/components/schemas/Selement'

    Selement:
      type: object
      title: Selement
      description: Selement Entity
      properties:
        elements:
          type: array
          items:
            $ref: '#/components/schemas/Element'
        label:
          type: string
          example: '2'
        label_location:
          type: string
          example: '3'
        elementtype:
          type: integer
          example: 2
        iconid_off:
          type: string
          example: '2'
        iconid_disabled:
          type: string
          example: '2'
        iconid_maintenance:
          type: string
          example: '2'
        iconid_on:
          type: string
          example: '2'
        x:
          type: integer
          example: 100
        y:
          type: integer
          example: 150

    Element:
      type: object
      title: Element
      description: Element Entity
      properties:
        triggerid:
          type: string
          example: '13467'

    ExampleTriggers:
      type: object
      title: ''
      description: ' Entity'
      properties:
        filter:
          type: object
          example: { 'hostid': 10084 }
